version: "3"
services:
   prep:
      image: iconloop/icon2-node
      container_name: "node"
      network_mode: host
      restart: "on-failure"
      stdin_open: true
      environment:
         SERVICE: "MainNet" # MainNet, SejongNet  ## network type
         IS_AUTOGEN_CERT: "true"
         GOLOOP_LOG_LEVEL: "debug" # trace, debug, info, warn, error, fatal, panic
         GOLOOP_KEY_PLUGIN: "/goloop/config/wallet_amd.so" # change to wallet.so if arm
         GOLOOP_KEY_PLUGIN_OPTIONS: '{"region":"REGION","access_key_id":"ACCESS_KEY","secret_access_key":"SECRET_KEY","key_id":"KEY_ID"}' # atm support kms aws only (todo add more)

         #FASTEST_START: "true"    # It can be restored from latest Snapshot DB.

         ROLE: 3 # Validator = 3, API Endpoint = 0

      cap_add:
         - SYS_TIME

      volumes:
         - ./data:/goloop/data # mount a data volumes
         - ./config:/goloop/config # mount a config volumes ,Put your used keystore file here.
         - ./logs:/goloop/logs
      ports:
         - 9000:9000
         - 7100:7100
